/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Backend liveness check. */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/test/ping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Connectivity smoke test for renderer -> main -> backend chain. */
    get: operations['testPing'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get application settings. */
    get: operations['settingsGet'];
    /** Update application settings. */
    put: operations['settingsUpdate'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/audit/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit events. */
    get: operations['auditListEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/audit/events/{eventId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one audit event detail. */
    get: operations['auditGetEventById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/servers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List SSH servers. */
    get: operations['sshListServers'];
    put?: never;
    /** Create SSH server configuration. */
    post: operations['sshCreateServer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/servers/{serverId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update SSH server configuration. */
    put: operations['sshUpdateServer'];
    post?: never;
    /** Delete SSH server configuration. */
    delete: operations['sshDeleteServer'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/servers/{serverId}/credentials': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get SSH server credentials for editor form prefill. */
    get: operations['sshGetServerCredentials'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/keychains': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List SSH keychains. */
    get: operations['sshListKeychains'];
    put?: never;
    /** Create SSH keychain. */
    post: operations['sshCreateKeychain'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/keychains/{keychainId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update SSH keychain. */
    put: operations['sshUpdateKeychain'];
    post?: never;
    /** Delete SSH keychain. */
    delete: operations['sshDeleteKeychain'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/keychains/{keychainId}/credentials': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get SSH keychain credentials for editor form prefill. */
    get: operations['sshGetKeychainCredentials'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/folders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List SSH folders. */
    get: operations['sshListFolders'];
    put?: never;
    /** Create SSH folder. */
    post: operations['sshCreateFolder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/folders/{folderId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update SSH folder. */
    put: operations['sshUpdateFolder'];
    post?: never;
    /** Delete SSH folder. */
    delete: operations['sshDeleteFolder'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List SSH tags. */
    get: operations['sshListTags'];
    put?: never;
    /** Create SSH tag. */
    post: operations['sshCreateTag'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a live SSH terminal session. */
    post: operations['sshCreateSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Close a live SSH terminal session. */
    delete: operations['sshCloseSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ssh/trusted-host-keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trust a host fingerprint for a server. */
    post: operations['sshTrustFingerprint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an SFTP file-system session. */
    post: operations['sftpCreateSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/entries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List entries in one remote SFTP directory. */
    get: operations['sftpListDirectory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/entries/details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get detailed metadata for selected remote SFTP entries. */
    post: operations['sftpGetEntryDetails'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/file': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one remote SFTP file for preview. */
    get: operations['sftpReadFile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Download one remote SFTP file to a local path. */
    post: operations['sftpDownloadFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload one locally edited SFTP temp file back to the remote path. */
    post: operations['sftpUploadFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/directories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create one remote SFTP directory. */
    post: operations['sftpCreateDirectory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create one empty remote SFTP file. */
    post: operations['sftpCreateFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/rename': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rename or move one remote SFTP entry. */
    post: operations['sftpRenameEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/copy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Copy one remote SFTP entry. */
    post: operations['sftpCopyEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/entries/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete one remote SFTP entry. */
    post: operations['sftpDeleteEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}/batch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run one ordered batch operation across remote SFTP entries. */
    post: operations['sftpBatchOperation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sftp/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Close an SFTP file-system session. */
    delete: operations['sftpCloseSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/local-terminals/profiles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List local terminal profiles available on host. */
    get: operations['localTerminalListProfiles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/local-terminals/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a live local terminal session. */
    post: operations['localTerminalCreateSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/local-terminals/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Close a live local terminal session. */
    delete: operations['localTerminalCloseSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/port-forwards/rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List persisted SSH port-forwarding rules. */
    get: operations['portForwardListRules'];
    put?: never;
    /** Create one persisted SSH port-forwarding rule. */
    post: operations['portForwardCreateRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/port-forwards/rules/{ruleId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update one stopped SSH port-forwarding rule. */
    put: operations['portForwardUpdateRule'];
    post?: never;
    /** Delete one stopped SSH port-forwarding rule. */
    delete: operations['portForwardDeleteRule'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/port-forwards/rules/{ruleId}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start one persisted SSH port-forwarding rule. */
    post: operations['portForwardStartRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/port-forwards/rules/{ruleId}/stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stop one active SSH port-forwarding rule. */
    post: operations['portForwardStopRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      /** @enum {string} */
      status: 'ok';
      /** Format: date-time */
      timestamp: string;
    };
    ApiMeta: {
      code: string;
      message: string;
      requestId: string;
      /** Format: date-time */
      timestamp: string;
    };
    ApiError: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code:
        | 'COMMON_INTERNAL_SERVER_ERROR'
        | 'AUTH_INVALID_TOKEN'
        | 'SETTINGS_VALIDATION_FAILED'
        | 'SSH_VALIDATION_FAILED'
        | 'SSH_SERVER_CONFLICT'
        | 'SSH_FOLDER_CONFLICT'
        | 'SSH_TAG_CONFLICT'
        | 'SSH_KEYCHAIN_CONFLICT'
        | 'SSH_NOT_FOUND'
        | 'SSH_HOST_UNTRUSTED'
        | 'SSH_SESSION_NOT_FOUND'
        | 'SSH_KEYCHAIN_IN_USE'
        | 'SFTP_SESSION_NOT_FOUND'
        | 'SFTP_VALIDATION_FAILED'
        | 'SFTP_OPERATION_FAILED'
        | 'SFTP_UPLOAD_CONFLICT'
        | 'AUDIT_VALIDATION_FAILED'
        | 'AUDIT_EVENT_NOT_FOUND'
        | 'LOCAL_TERMINAL_VALIDATION_FAILED'
        | 'LOCAL_TERMINAL_PROFILE_NOT_FOUND'
        | 'PORT_FORWARD_VALIDATION_FAILED'
        | 'PORT_FORWARD_RULE_NOT_FOUND'
        | 'PORT_FORWARD_RULE_ACTIVE'
        | 'PORT_FORWARD_START_FAILED'
        | 'PORT_FORWARD_STOP_FAILED';
      /** @enum {boolean} */
      success: false;
    };
    /** @enum {string} */
    SshAuthType: 'password' | 'key' | 'both';
    /** @enum {string} */
    SshKeychainVisibility: 'hidden' | 'shared';
    TestPingData: {
      /** @enum {string} */
      service: 'cosmosh-backend';
      /** @enum {string} */
      mode: 'electron-main' | 'standalone';
      authenticated: boolean;
      capabilities: ('ssh' | 'sftp' | 'port-forward')[];
    };
    TestPingSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'TEST_PING_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['TestPingData'];
    };
    /** @description Application settings values. Property definitions, types, defaults, constraints, and enum sets are managed by the settings registry at packages/api-contract/src/settings-registry.ts. This schema is intentionally loose; runtime validation lives in code. */
    SettingsValues: {
      [key: string]: unknown;
    };
    SettingsScope: {
      accountId?: string;
      deviceId: string;
    };
    SettingsResource: {
      scope: components['schemas']['SettingsScope'];
      revision: number;
      /** Format: date-time */
      updatedAt: string;
      values: components['schemas']['SettingsValues'];
    };
    SettingsGetData: {
      item: components['schemas']['SettingsResource'];
    };
    SettingsUpdateRequest: {
      scope?: components['schemas']['SettingsScope'];
      values: components['schemas']['SettingsValues'];
    };
    SettingsUpdateData: {
      item: components['schemas']['SettingsResource'];
    };
    /** @enum {string} */
    AuditEventOutcome: 'success' | 'failure';
    /** @enum {string} */
    AuditEventSeverity: 'info' | 'warning' | 'critical';
    AuditEventListItem: {
      eventId: string;
      /** Format: date-time */
      occurredAt: string;
      category: string;
      action: string;
      outcome: components['schemas']['AuditEventOutcome'];
      severity: components['schemas']['AuditEventSeverity'];
      scopeAccountId: string;
      scopeDeviceId: string;
      entityType?: string;
      entityId?: string;
      sessionId?: string;
      requestId?: string;
      correlationId?: string;
      relatedRecordId?: string;
    };
    AuditEventDetailItem: components['schemas']['AuditEventListItem'] & {
      metadata: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      retentionUntilAt: string;
    };
    AuditEventPagination: {
      page: number;
      pageSize: number;
      total: number;
      hasMore: boolean;
    };
    AuditEventListData: {
      items: components['schemas']['AuditEventListItem'][];
      pagination: components['schemas']['AuditEventPagination'];
    };
    AuditEventDetailData: {
      item: components['schemas']['AuditEventDetailItem'];
    };
    SshFolder: {
      id: string;
      name: string;
      iconKey: string;
      colorKey: components['schemas']['SshVisualColorKey'];
      note?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SshTag: {
      id: string;
      name: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SshLoginAudit: {
      id: string;
      /** Format: date-time */
      attemptedAt: string;
      /** @enum {string} */
      result: 'success' | 'failed';
      failureReason?: string;
      clientIp?: string;
      sessionId?: string;
      /** Format: date-time */
      sessionStartedAt?: string;
      /** Format: date-time */
      sessionEndedAt?: string;
      commandCount: number;
    };
    SshServerListItem: {
      id: string;
      name: string;
      iconKey: string;
      colorKey: components['schemas']['SshVisualColorKey'];
      host: string;
      port: number;
      username: string;
      keychainId: string;
      authType: components['schemas']['SshAuthType'];
      strictHostKey?: boolean;
      enableSshCompression?: boolean;
      disableCharacterWidthCompatibilityMode?: boolean;
      terminalClipboardAccess?: components['schemas']['TerminalClipboardAccess'];
      hasPassword: boolean;
      hasPrivateKey: boolean;
      note?: string;
      folder?: components['schemas']['SshFolder'];
      tags?: components['schemas']['SshTag'][];
      systemHostname?: string;
      systemOs?: string;
      systemArch?: string;
      systemKernel?: string;
      /** Format: date-time */
      lastSystemSyncAt?: string;
      lastLoginAudit?: components['schemas']['SshLoginAudit'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SshServerCreateRequest: {
      name: string;
      host: string;
      port: number;
      username: string;
      keychainId?: string;
      authType?: components['schemas']['SshAuthType'];
      strictHostKey?: boolean;
      enableSshCompression?: boolean;
      disableCharacterWidthCompatibilityMode?: boolean;
      terminalClipboardAccess?: components['schemas']['TerminalClipboardAccess'];
      iconKey?: string;
      colorKey?: components['schemas']['SshVisualColorKey'];
      password?: string;
      privateKey?: string;
      privateKeyPassphrase?: string;
      folderId?: string;
      tagIds?: string[];
      note?: string;
    };
    SshFolderCreateRequest: {
      name: string;
      iconKey?: string;
      colorKey?: components['schemas']['SshVisualColorKey'];
      note?: string;
    };
    SshFolderUpdateRequest: {
      name: string;
      iconKey?: string;
      colorKey?: components['schemas']['SshVisualColorKey'];
      note?: string;
    };
    /** @enum {string} */
    SshVisualColorKey: 'slate' | 'blue' | 'emerald' | 'violet' | 'amber' | 'rose' | 'cyan' | 'indigo' | 'teal' | 'lime';
    SshTagCreateRequest: {
      name: string;
    };
    SshSessionCreateRequest: {
      serverId: string;
      /** @default 120 */
      cols: number;
      /** @default 32 */
      rows: number;
      /** @default xterm-256color */
      term: string;
      /** @default 45 */
      connectTimeoutSec: number;
      strictHostKey?: boolean;
      enableSshCompression?: boolean;
    };
    /** @enum {string} */
    TerminalClipboardAccess: 'off' | 'writeAskRead' | 'readWrite' | 'askAlways';
    SshTrustFingerprintRequest: {
      serverId: string;
      fingerprintSha256: string;
      /**
       * @default sha256
       * @enum {string}
       */
      algorithm: 'sha256';
    };
    SshHostVerificationRequiredData: {
      serverId: string;
      host: string;
      port: number;
      /** @enum {string} */
      algorithm: 'sha256';
      fingerprint: string;
    };
    SshHostVerificationRequired: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_HOST_UNTRUSTED';
      /** @enum {boolean} */
      success: false;
      data: components['schemas']['SshHostVerificationRequiredData'];
    };
    SshServerListData: {
      items: components['schemas']['SshServerListItem'][];
    };
    SshFolderListData: {
      items: components['schemas']['SshFolder'][];
    };
    SshTagListData: {
      items: components['schemas']['SshTag'][];
    };
    SshServerCreateData: {
      item: components['schemas']['SshServerListItem'];
    };
    SshServerCredentialsData: {
      authType: components['schemas']['SshAuthType'];
      password?: string;
      privateKey?: string;
      privateKeyPassphrase?: string;
    };
    SshKeychainListItem: {
      id: string;
      name: string;
      iconKey: string;
      colorKey: components['schemas']['SshVisualColorKey'];
      authType: components['schemas']['SshAuthType'];
      visibility: components['schemas']['SshKeychainVisibility'];
      hasPassword: boolean;
      hasPrivateKey: boolean;
      note?: string;
      folder?: components['schemas']['SshFolder'];
      tags: components['schemas']['SshTag'][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SshKeychainListData: {
      items: components['schemas']['SshKeychainListItem'][];
    };
    SshKeychainCreateRequest: {
      name: string;
      iconKey?: string;
      colorKey?: components['schemas']['SshVisualColorKey'];
      authType: components['schemas']['SshAuthType'];
      visibility?: components['schemas']['SshKeychainVisibility'];
      folderId?: string;
      tagIds?: string[];
      password?: string;
      privateKey?: string;
      privateKeyPassphrase?: string;
      note?: string;
    };
    SshKeychainUpdateRequest: components['schemas']['SshKeychainCreateRequest'];
    SshKeychainCreateData: {
      item: components['schemas']['SshKeychainListItem'];
    };
    SshKeychainCredentialsData: {
      authType: components['schemas']['SshAuthType'];
      password?: string;
      privateKey?: string;
      privateKeyPassphrase?: string;
    };
    SshFolderCreateData: {
      item: components['schemas']['SshFolder'];
    };
    SshTagCreateData: {
      item: components['schemas']['SshTag'];
    };
    SshSessionCreateData: {
      sessionId: string;
      serverId: string;
      websocketUrl: string;
      websocketToken: string;
    };
    SshTrustFingerprintData: {
      /** @enum {boolean} */
      trusted: true;
    };
    /** @enum {string} */
    PortForwardRuleType: 'local' | 'remote' | 'dynamic';
    /** @enum {string} */
    PortForwardRuleStatus: 'stopped' | 'running';
    PortForwardRuleRuntime: {
      status: components['schemas']['PortForwardRuleStatus'];
      activeConnectionCount: number;
      boundHost?: string;
      boundPort?: number;
      /** Format: date-time */
      startedAt?: string;
      lastError?: string;
    };
    PortForwardRuleListItem: {
      id: string;
      name: string;
      type: components['schemas']['PortForwardRuleType'];
      serverId: string;
      serverName?: string;
      localBindHost?: string;
      localBindPort?: number;
      remoteBindHost?: string;
      remoteBindPort?: number;
      targetHost?: string;
      targetPort?: number;
      note?: string;
      /** Format: date-time */
      lastStartedAt?: string;
      /** Format: date-time */
      lastStoppedAt?: string;
      lastFailureMessage?: string;
      runtime: components['schemas']['PortForwardRuleRuntime'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PortForwardRuleCreateRequest: {
      name: string;
      serverId: string;
      type: components['schemas']['PortForwardRuleType'];
      localBindHost?: string;
      localBindPort?: number;
      remoteBindHost?: string;
      remoteBindPort?: number;
      targetHost?: string;
      targetPort?: number;
      note?: string;
    };
    PortForwardRuleUpdateRequest: components['schemas']['PortForwardRuleCreateRequest'];
    PortForwardRuleListData: {
      items: components['schemas']['PortForwardRuleListItem'][];
    };
    PortForwardRuleData: {
      item: components['schemas']['PortForwardRuleListItem'];
    };
    SftpSessionCreateRequest: {
      serverId: string;
      initialPath?: string;
      connectTimeoutSec?: number;
      strictHostKey?: boolean;
    };
    SftpPathRequest: {
      path: string;
    };
    SftpCreateDirectoryRequest: components['schemas']['SftpPathRequest'];
    SftpCreateFileRequest: components['schemas']['SftpPathRequest'];
    SftpDownloadFileRequest: {
      path: string;
      localPath: string;
    };
    SftpUploadFileRequest: {
      path: string;
      localPath: string;
      /** Format: int64 */
      expectedSize: number;
      /** Format: date-time */
      expectedModifiedAt: string;
      /** @description Explicitly replace the remote file even when its size or modified time no longer matches the opening snapshot. */
      overwrite?: boolean;
    };
    SftpRenameRequest: {
      sourcePath: string;
      targetPath: string;
    };
    SftpCopyRequest: {
      sourcePath: string;
      targetPath: string;
    };
    SftpDeleteRequest: components['schemas']['SftpPathRequest'] & {
      /** @default true */
      recursive: boolean;
    };
    /** @enum {string} */
    SftpBatchOperationType: 'copy' | 'move' | 'delete';
    SftpBatchOperationItemRequest: {
      path: string;
      type: components['schemas']['SftpEntryType'];
    };
    SftpBatchOperationRequest: {
      operation: components['schemas']['SftpBatchOperationType'];
      entries: components['schemas']['SftpBatchOperationItemRequest'][];
      /** @description Required when operation is copy or move. */
      targetDirectoryPath?: string;
    };
    /** @enum {string} */
    SftpBatchOperationItemStatus: 'success' | 'failed' | 'skipped';
    SftpBatchOperationItemResult: {
      path: string;
      type: components['schemas']['SftpEntryType'];
      targetPath?: string;
      status: components['schemas']['SftpBatchOperationItemStatus'];
      message?: string;
    };
    /** @enum {string} */
    SftpEntryType: 'directory' | 'file' | 'symlink' | 'other';
    SftpEntry: {
      name: string;
      path: string;
      parentPath?: string;
      type: components['schemas']['SftpEntryType'];
      /** Format: int64 */
      size: number;
      mode: number;
      permissions: string;
      permissionOctal: string;
      uid: number;
      gid: number;
      /** Format: date-time */
      modifiedAt: string;
      /** Format: date-time */
      accessedAt: string;
      extension: string;
      shellEscapedPath: string;
      isHidden: boolean;
      longname?: string;
      symlinkTarget?: components['schemas']['SftpSymlinkTarget'];
    };
    /** @enum {string} */
    SftpSymlinkTargetStatus: 'exists' | 'broken' | 'permission-denied' | 'unknown';
    SftpSymlinkTarget: {
      status: components['schemas']['SftpSymlinkTargetStatus'];
      /** @description Raw target returned by readlink. */
      path?: string;
      /** @description Absolute target path resolved from the link parent when possible. */
      resolvedPath?: string;
      isAbsolute?: boolean;
      type?: components['schemas']['SftpEntryType'];
      /** Format: int64 */
      size?: number;
      mode?: number;
      permissions?: string;
      permissionOctal?: string;
      /** Format: date-time */
      modifiedAt?: string;
      /** Format: date-time */
      accessedAt?: string;
      message?: string;
    };
    SftpEntryDetailsRequest: {
      paths: string[];
    };
    /** @enum {string} */
    SftpEntryDetailsItemStatus: 'success' | 'failed';
    SftpEntryDetailsItem: {
      path: string;
      status: components['schemas']['SftpEntryDetailsItemStatus'];
      entry?: components['schemas']['SftpEntry'];
      message?: string;
    };
    SftpSessionCreateData: {
      sessionId: string;
      serverId: string;
      initialPath: string;
      currentPath: string;
      /** @enum {boolean} */
      readOnly: false;
    };
    SftpDirectoryListData: {
      sessionId: string;
      path: string;
      parentPath?: string;
      entries: components['schemas']['SftpEntry'][];
    };
    SftpEntryDetailsData: {
      sessionId: string;
      requestedCount: number;
      entries: components['schemas']['SftpEntryDetailsItem'][];
    };
    SftpOperationData: {
      sessionId: string;
      path: string;
      targetPath?: string;
      /** Format: int64 */
      size?: number;
      /** Format: date-time */
      modifiedAt?: string;
    };
    SftpBatchOperationData: {
      sessionId: string;
      operation: components['schemas']['SftpBatchOperationType'];
      totalCount: number;
      completedCount: number;
      failedCount: number;
      skippedCount: number;
      stoppedOnFailure: boolean;
      results: components['schemas']['SftpBatchOperationItemResult'][];
    };
    SftpReadFileData: {
      sessionId: string;
      path: string;
      /** @enum {string} */
      encoding: 'utf8';
      content: string;
      /** Format: int64 */
      size: number;
      truncated: boolean;
    };
    SftpDownloadFileData: {
      sessionId: string;
      path: string;
      localPath: string;
      /** Format: int64 */
      size: number;
    };
    LocalTerminalProfile: {
      id: string;
      name: string;
      command: string;
      executablePath: string;
      args: string[];
    };
    LocalTerminalProfileListData: {
      items: components['schemas']['LocalTerminalProfile'][];
    };
    LocalTerminalSessionCreateRequest: {
      profileId: string;
      /** @default 120 */
      cols: number;
      /** @default 32 */
      rows: number;
      /** @default xterm-256color */
      term: string;
      cwd?: string;
    };
    LocalTerminalSessionCreateData: {
      sessionId: string;
      profileId: string;
      websocketUrl: string;
      websocketToken: string;
    };
    LocalTerminalProfileListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'LOCAL_TERMINAL_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['LocalTerminalProfileListData'];
    };
    LocalTerminalSessionCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'LOCAL_TERMINAL_SESSION_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['LocalTerminalSessionCreateData'];
    };
    SettingsGetSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SETTINGS_GET_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SettingsGetData'];
    };
    SettingsUpdateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SETTINGS_UPDATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SettingsUpdateData'];
    };
    AuditEventListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'AUDIT_EVENT_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['AuditEventListData'];
    };
    AuditEventDetailSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'AUDIT_EVENT_DETAIL_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['AuditEventDetailData'];
    };
    SshServerListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_SERVER_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshServerListData'];
    };
    SshServerCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_SERVER_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshServerCreateData'];
    };
    SshServerUpdateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_SERVER_UPDATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshServerCreateData'];
    };
    SshServerCredentialsSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_SERVER_CREDENTIALS_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshServerCredentialsData'];
    };
    SshKeychainListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_KEYCHAIN_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshKeychainListData'];
    };
    SshKeychainCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_KEYCHAIN_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshKeychainCreateData'];
    };
    SshKeychainUpdateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_KEYCHAIN_UPDATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshKeychainCreateData'];
    };
    SshKeychainCredentialsSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_KEYCHAIN_CREDENTIALS_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshKeychainCredentialsData'];
    };
    SshFolderListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_FOLDER_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshFolderListData'];
    };
    SshFolderCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_FOLDER_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshFolderCreateData'];
    };
    SshFolderUpdateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_FOLDER_UPDATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshFolderCreateData'];
    };
    SshTagListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_TAG_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshTagListData'];
    };
    SshTagCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_TAG_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshTagCreateData'];
    };
    SshSessionCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_SESSION_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshSessionCreateData'];
    };
    SshTrustFingerprintSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SSH_TRUST_FINGERPRINT_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SshTrustFingerprintData'];
    };
    PortForwardRuleListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'PORT_FORWARD_RULE_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['PortForwardRuleListData'];
    };
    PortForwardRuleCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'PORT_FORWARD_RULE_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['PortForwardRuleData'];
    };
    PortForwardRuleUpdateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'PORT_FORWARD_RULE_UPDATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['PortForwardRuleData'];
    };
    PortForwardRuleStartSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'PORT_FORWARD_RULE_START_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['PortForwardRuleData'];
    };
    PortForwardRuleStopSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'PORT_FORWARD_RULE_STOP_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['PortForwardRuleData'];
    };
    SftpSessionCreateSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SFTP_SESSION_CREATE_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SftpSessionCreateData'];
    };
    SftpDirectoryListSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SFTP_DIRECTORY_LIST_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SftpDirectoryListData'];
    };
    SftpEntryDetailsSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SFTP_ENTRY_DETAILS_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SftpEntryDetailsData'];
    };
    SftpOperationSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SFTP_OPERATION_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SftpOperationData'];
    };
    SftpBatchOperationSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SFTP_OPERATION_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SftpBatchOperationData'];
    };
    SftpReadFileSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SFTP_FILE_READ_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SftpReadFileData'];
    };
    SftpDownloadFileSuccess: components['schemas']['ApiMeta'] & {
      /** @enum {string} */
      code: 'SFTP_OPERATION_OK';
      /** @enum {boolean} */
      success: true;
      data: components['schemas']['SftpDownloadFileData'];
    };
  };
  responses: never;
  parameters: {
    LocaleHeader: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Backend service is alive. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  testPing: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful ping response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TestPingSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  settingsGet: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Settings fetched. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsGetSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  settingsUpdate: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingsUpdateRequest'];
      };
    };
    responses: {
      /** @description Settings updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsUpdateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  auditListEvents: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
        startAt?: string;
        endAt?: string;
        category?: string;
        outcome?: string;
        entityType?: string;
        entityId?: string;
        keyword?: string;
      };
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audit events listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditEventListSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  auditGetEventById: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        eventId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Audit event detail fetched. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditEventDetailSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Audit event not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshListServers: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH servers listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshServerListSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshCreateServer: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshServerCreateRequest'];
      };
    };
    responses: {
      /** @description SSH server created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshServerCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Conflict with existing server. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshUpdateServer: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        serverId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshServerCreateRequest'];
      };
    };
    responses: {
      /** @description SSH server updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshServerUpdateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Conflict with existing server. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshDeleteServer: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        serverId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH server deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshGetServerCredentials: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        serverId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH server credentials fetched. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshServerCredentialsSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshListKeychains: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH keychains listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshKeychainListSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshCreateKeychain: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshKeychainCreateRequest'];
      };
    };
    responses: {
      /** @description SSH keychain created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshKeychainCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Conflict with existing keychain. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshUpdateKeychain: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        keychainId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshKeychainUpdateRequest'];
      };
    };
    responses: {
      /** @description SSH keychain updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshKeychainUpdateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH keychain not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshDeleteKeychain: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        keychainId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH keychain deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH keychain not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH keychain is in use. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshGetKeychainCredentials: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        keychainId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH keychain credentials fetched. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshKeychainCredentialsSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH keychain not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshListFolders: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH folders listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshFolderListSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshCreateFolder: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshFolderCreateRequest'];
      };
    };
    responses: {
      /** @description SSH folder created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshFolderCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Folder already exists. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshUpdateFolder: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        folderId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshFolderUpdateRequest'];
      };
    };
    responses: {
      /** @description SSH folder updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshFolderUpdateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH folder not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Folder already exists. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshDeleteFolder: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        folderId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH folder deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description SSH folder not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshListTags: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSH tags listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshTagListSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshCreateTag: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshTagCreateRequest'];
      };
    };
    responses: {
      /** @description SSH tag created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshTagCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Tag already exists. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshCreateSession: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshSessionCreateRequest'];
      };
    };
    responses: {
      /** @description SSH session is ready for websocket streaming. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshSessionCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Host fingerprint is not trusted. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshHostVerificationRequired'];
        };
      };
    };
  };
  sshCloseSession: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session closed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sshTrustFingerprint: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SshTrustFingerprintRequest'];
      };
    };
    responses: {
      /** @description Host fingerprint has been trusted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshTrustFingerprintSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpCreateSession: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpSessionCreateRequest'];
      };
    };
    responses: {
      /** @description SFTP session is ready for file-system operations. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpSessionCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Host fingerprint is not trusted. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SshHostVerificationRequired'];
        };
      };
    };
  };
  sftpListDirectory: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory entries listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpDirectoryListSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or directory not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpGetEntryDetails: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpEntryDetailsRequest'];
      };
    };
    responses: {
      /** @description Detailed entry metadata fetched. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpEntryDetailsSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpReadFile: {
    parameters: {
      query: {
        path: string;
        maxBytes?: number;
      };
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File content read. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpReadFileSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or file not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpDownloadFile: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpDownloadFileRequest'];
      };
    };
    responses: {
      /** @description File downloaded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpDownloadFileSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or file not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpUploadFile: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpUploadFileRequest'];
      };
    };
    responses: {
      /** @description File uploaded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpOperationSuccess'];
        };
      };
      /** @description Validation failed or upload failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or file not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Remote file changed after it was opened. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpCreateDirectory: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpCreateDirectoryRequest'];
      };
    };
    responses: {
      /** @description Directory created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpOperationSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpCreateFile: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpCreateFileRequest'];
      };
    };
    responses: {
      /** @description File created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpOperationSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpRenameEntry: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpRenameRequest'];
      };
    };
    responses: {
      /** @description Entry renamed or moved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpOperationSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or entry not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpCopyEntry: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpCopyRequest'];
      };
    };
    responses: {
      /** @description Entry copied. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpOperationSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or entry not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpDeleteEntry: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpDeleteRequest'];
      };
    };
    responses: {
      /** @description Entry deleted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpOperationSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or entry not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpBatchOperation: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SftpBatchOperationRequest'];
      };
    };
    responses: {
      /** @description Batch operation completed. The summary reports failed and skipped entries when fail-fast stops execution. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SftpBatchOperationSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session or entry not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  sftpCloseSession: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session closed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  localTerminalListProfiles: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Local terminal profiles listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LocalTerminalProfileListSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  localTerminalCreateSession: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LocalTerminalSessionCreateRequest'];
      };
    };
    responses: {
      /** @description Local terminal session is ready for websocket streaming. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LocalTerminalSessionCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Profile not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  localTerminalCloseSession: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        sessionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session closed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Session not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  portForwardListRules: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Port-forwarding rules listed. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PortForwardRuleListSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  portForwardCreateRule: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PortForwardRuleCreateRequest'];
      };
    };
    responses: {
      /** @description Port-forwarding rule created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PortForwardRuleCreateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  portForwardUpdateRule: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        ruleId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PortForwardRuleUpdateRequest'];
      };
    };
    responses: {
      /** @description Port-forwarding rule updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PortForwardRuleUpdateSuccess'];
        };
      };
      /** @description Validation failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Rule or server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Rule is active. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  portForwardDeleteRule: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        ruleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Port-forwarding rule deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Rule not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Rule is active. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  portForwardStartRule: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        ruleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Port-forwarding rule started. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PortForwardRuleStartSuccess'];
        };
      };
      /** @description Start failed. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Rule or server not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Rule is already active or host fingerprint is not trusted. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'] | components['schemas']['SshHostVerificationRequired'];
        };
      };
    };
  };
  portForwardStopRule: {
    parameters: {
      query?: never;
      header?: {
        'x-cosmosh-locale'?: components['parameters']['LocaleHeader'];
      };
      path: {
        ruleId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Port-forwarding rule stopped. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PortForwardRuleStopSuccess'];
        };
      };
      /** @description Authentication failed. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Rule not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
}
